name: Laravel CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, ctype, fileinfo, tokenizer, dom, pdo_mysql
        coverage: none

    - name: Copy environment file
      run: cp .env.example .env

    # Install dependencies FIRST
    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist

    # Then generate key
    - name: Generate app key
      run: php artisan key:generate

    - name: Set up permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run database migrations
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate --force

    - name: Run tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test

  # Add this job for deployment (example)
  # deploy:
  #   if: github.ref == 'refs/heads/main'
  #   needs: [laravel-tests]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
        
  #     - name: Deploy to production
  #       run: echo "Add your deployment commands here"